`timescale 1ns / 1ns

//****************************************VSCODE PLUG-IN**********************************//
//----------------------------------------------------------------------------------------
// IDE :                   VSCODE     
// VSCODE plug-in version: Verilog-Hdl-Format-4.3.20260413
// VSCODE plug-in author : Jiang Percy
//----------------------------------------------------------------------------------------
//****************************************Copyright (c)***********************************//
// Copyright(C)            ORI2333
// All rights reserved     
// File name:              
// Last modified Date:     2026/04/19 00:31:40
// Last Version:           V1.0
// Descriptions:           
//----------------------------------------------------------------------------------------
// Created by:             ORI2333
// Created date:           2026/04/19 00:31:40
// mail      :             ori2333.zh@gmail.com
// Version:                V1.0
// TEXT NAME:              sc1336_hdmi.sv
// PATH:                   fpga/sc1336_hdmi_isp/rtl/sc1336_hdmi.sv
// Descriptions:           
//                         
//----------------------------------------------------------------------------------------
//****************************************************************************************//

module sc1336_hdmi(
    // global clock and reset
    input                               clk_50m                    ,// 50MHz
    input                               rst_n                      ,

    // DVP Interface
    output                              cmos_xclk                  ,// 27MHz or 24MHz, generated by PLL
    input                               cmos_pclk                  ,
    input                               cmos_vsync                 ,
    input                               cmos_href                  ,
    input                [   7: 0]      cmos_data                  ,

    output                              cmos_sclk                  ,
    inout                               cmos_sdat                  ,

    // UART debug interface
    input                               uart_rxd                   ,
    output                              uart_txd                   ,

	//DDR3 Interface (Internal)
    inout                [  31: 0]      ddr3_dq                    ,
    inout                [   3: 0]      ddr3_dqs_n                 ,
    inout                [   3: 0]      ddr3_dqs_p                 ,
    output               [   3: 0]      ddr3_dm                    ,

    output               [   0: 0]      ddr3_cs_n                  ,
    output                              ddr3_reset_n               ,
	
    output               [   0: 0]      ddr3_ck_p                  ,
    output               [   0: 0]      ddr3_ck_n                  ,
    output               [   0: 0]      ddr3_cke                   ,
	
    output                              ddr3_ras_n                 ,
    output                              ddr3_cas_n                 ,
    output                              ddr3_we_n                  ,
    output               [   0: 0]      ddr3_odt                   ,
	
    output               [  13: 0]      ddr3_addr                  ,
    output               [   2: 0]      ddr3_ba                    ,

    //lcd interface
    output                              lcd_dclk                   ,// 720P@60FPS 74.25MHz
    output                              lcd_hs                     ,
    output                              lcd_vs                     ,
    output                              lcd_de                     ,

    output               [   7: 0]      lcd_red                    ,
    output               [   7: 0]      lcd_green                  ,
    output               [   7: 0]      lcd_blue                    
);
`define USE_ILA
    parameter              PIXEL_DATA_WIDTH            = 8                    ;
    parameter              IMAGE_HSIZE                 = 1280                 ;
    parameter              IMAGE_YSIZE                 = 720                  ;

//=============================================================================
//  1. CLOCK & RESET MANAGEMENT
//=============================================================================
// clock control
wire                           clk_ctrl                   ;// 100MHz
wire                           clk_video                  ;// 74.25MHz
wire                           clk_cmos                   ;// 24MHz
wire                           clk_ddr_ref                ;// 250MHz
wire                           clk_ddr_ref_200m           ;// 200MHz (IDELAYCTRL ref)
wire                           clk_ila                    ;// 100MHz
wire                           clk_spare                  ;// 50MHz
wire                           sys_rst_n                  ;
wire                           cmos_sdat_in               ;
wire                           cmos_sdat_out              ;
wire                           cmos_sdat_oe               ;
wire                           mig_sys_rst                ;

sys_clk_ctrl#(
    .SYS_DELAY_TOP                      (24'd2500_000              ) // ~50ms delay @50MHz
)u_sys_clk_ctrl(
    // Clock and reset inputs
    .clk_in                             (clk_50m                   ),
    .ext_rst_n                          (rst_n                     ),
    // Clock and reset outputs
    .clk_out                            (                          ),// 100Mhz
    .clk_ctrl                           (clk_ctrl                  ),// 100MHz
    .clk_video                          (clk_video                 ),// 74.25MHz
    .clk_cmos                           (clk_cmos                  ),// 24MHz
    .clk_ddr_ref                        (clk_ddr_ref               ),// 250MHz
    .clk_ddr_ref_200m                   (clk_ddr_ref_200m          ),// 200MHz
    .clk_ila                            (clk_ila                   ),// 100MHz
    .clk_spare                          (clk_spare                 ),// 50MHz
    .sys_rst_n                          (sys_rst_n                 ),
    .mig_sys_rst                        (mig_sys_rst               )
);

assign     cmos_xclk    = clk_cmos     ;
assign     cmos_sdat_in = cmos_sdat    ;
assign     cmos_sdat    = (cmos_sdat_oe && (cmos_sdat_out == 1'b0)) ? 1'b0 : 1'bz;



//=============================================================================
//  2. SYSTEM CONFIG & UART DEBUG
//=============================================================================
// UART Debug (115200 bps, clk_ctrl=100MHz)
//   'L'=LCD  'D'=dynamic XOR  'X'=static XOR  'G'=gray
//   'S'/'R'=sensor RAW gray  'I'=demosaic RGB  'W'=RGB+AWB  'C'=RGB+AWB+crop
//   '0'..'3'=set Bayer mirror phase
//   'r'/'f'=red gain +/-    'g'/'v'=green gain +/-
//   'b'/'n'=blue gain +/-   'a'/'z'=global gain +/-
//   '+'/'-'=brightness +/-  'w'=reset gain/brightness defaults
//****************************************************************************************//
wire            [   7: 0]      uart_rx_data;
wire                           uart_rx_done;
wire                           uart_tx_busy;

reg             [   7: 0]      uart_tx_data;

uart_rx #(
    .CLK_FREQ                           (100_000_000               ),
    .UART_BPS                           (115200                    )
) u_uart_rx(
    .clk                                (clk_ctrl                  ),
    .rst_n                              (sys_rst_n                 ),
    .uart_rxd                           (uart_rxd                  ),
    .uart_rx_done                       (uart_rx_done              ),
    .uart_rx_data                       (uart_rx_data              )
);

uart_tx #(
    .CLK_FREQ                           (100_000_000               ),
    .UART_BPS                           (115200                    )
) u_uart_tx(
    .clk                                (clk_ctrl                  ),
    .rst_n                              (sys_rst_n                 ),
    .uart_tx_en                         (uart_rx_done              ),  // echo back
    .uart_tx_data                       (uart_tx_data              ),
    .uart_txd                           (uart_txd                  ),
    .uart_tx_busy                       (uart_tx_busy              )
);

// Command register
reg             [   7: 0]      dbg_cmd = 8'h00;
always @(posedge clk_ctrl) begin
    if (uart_rx_done)
        dbg_cmd <= uart_rx_data;
end

wire                           DBG_LCD  = (dbg_cmd == "L");
wire                           DBG_XOR  = (dbg_cmd == "X");   // DDR + static XOR   // LCD test (bypass DDR)
wire                           DBG_DDR  = (dbg_cmd == "D");   // DDR test with grayscale pattern
wire                           DBG_GRAY = (dbg_cmd == "G");   // DDR test with constant 0xA5
wire                           DBG_SEN  = (dbg_cmd == "S");   // Sensor
wire                           DBG_RAW  = (dbg_cmd == "R");   // Sensor RAW gray
wire                           DBG_ISP  = (dbg_cmd == "I");   // Bayer demosaic RGB
wire                           DBG_AWB  = (dbg_cmd == "W");   // RGB + manual AWB
wire                           DBG_CROP = (dbg_cmd == "C");   // RGB + manual AWB + boundary crop
wire                           DBG_MIR0 = (dbg_cmd == "0");   // Bayer phase 0
wire                           DBG_MIR1 = (dbg_cmd == "1");   // Bayer phase 1
wire                           DBG_MIR2 = (dbg_cmd == "2");   // Bayer phase 2
wire                           DBG_MIR3 = (dbg_cmd == "3");   // Bayer phase 3

wire                           CMD_R_GAIN_UP   = uart_rx_done && (uart_rx_data == "r");
wire                           CMD_R_GAIN_DN   = uart_rx_done && (uart_rx_data == "f");
wire                           CMD_G_GAIN_UP   = uart_rx_done && (uart_rx_data == "g");
wire                           CMD_G_GAIN_DN   = uart_rx_done && (uart_rx_data == "v");
wire                           CMD_B_GAIN_UP   = uart_rx_done && (uart_rx_data == "b");
wire                           CMD_B_GAIN_DN   = uart_rx_done && (uart_rx_data == "n");
wire                           CMD_ALL_GAIN_UP = uart_rx_done && (uart_rx_data == "a");
wire                           CMD_ALL_GAIN_DN = uart_rx_done && (uart_rx_data == "z");
wire                           CMD_BRIGHT_UP   = uart_rx_done && (uart_rx_data == "+");
wire                           CMD_BRIGHT_DN   = uart_rx_done && (uart_rx_data == "-");
wire                           CMD_AWB_RESET   = uart_rx_done && (uart_rx_data == "w");


//=============================================================================
//  3. I2C CONFIGURATION (SC1336)
//=============================================================================
// I2C Configuration for SC1336
wire            [   7: 0]      i2c_config_index           ;
wire            [  23: 0]      i2c_config_data            ;
wire            [   7: 0]      i2c_config_size            ;
wire                           i2c_config_done            ;

i2c_wr_16b8b#(
    .CLK_FREQ                           (100_000000                ),//100 MHz
    .I2C_FREQ                           (400_000                   ) //400 KHz(< 400KHz)
)u_i2c_wr_16b8b(
    // global clock
    .clk                                (clk_ctrl                  ),// 100MHz
    .rst_n                              (sys_rst_n                 ),

    // i2c interface     
    .i2c_sclk                           (cmos_sclk                 ),//i2c clock 400KHz
    .i2c_sdat_i                         (cmos_sdat_in              ),
    .i2c_sdat_o                         (cmos_sdat_out             ),
    .i2c_sdat_oe                        (cmos_sdat_oe              ),

    // user interface
    .i2c_config_size                    (i2c_config_size           ),//i2c config data counter
    .i2c_config_index                   (i2c_config_index          ),//i2c config reg index, read 2 reg and write xx reg
    .i2c_config_data                    ({8'h60, i2c_config_data}  ),//i2c config data
    .i2c_config_done                    (i2c_config_done           ) //i2c config timing complete
);

// I2C Configure Data of SC1336
i2c_sc1336_config u_i2c_sc1336_config(
    .LUT_INDEX                          (i2c_config_index          ),
    .LUT_DATA                           (i2c_config_data           ),
    .LUT_SIZE                           (i2c_config_size           )
);

//=============================================================================
//  4. CMOS SENSOR & ISP PROCESS (XYCrop)
//=============================================================================
wire                           ddr_init_done              ;// DDR3 init/calibration done
wire                           coms_ddr_init_done         ;// coms and ddr3 init/calibration done
assign     coms_ddr_init_done= i2c_config_done && ddr_init_done;

wire                           cmos_de                    ;
assign     cmos_de = 1'b1;                                  // DVP: every PCLK during HREF is valid
wire                           XYCrop_frame_vsync         ;
wire                           XYCrop_frame_href          ;
wire                           XYCrop_frame_de            ;
wire            [   7: 0]      XYCrop_frame_data          ;

Sensor_Image_XYCrop#(
    .IMAGE_HSIZE_SOURCE                 (IMAGE_HSIZE               ),
    .IMAGE_VSIZE_SOURCE                 (IMAGE_YSIZE               ),
    .IMAGE_HSIZE_TARGET                 (IMAGE_HSIZE               ),
    .IMAGE_YSIZE_TARGET                 (IMAGE_YSIZE               ),
    .PIXEL_DATA_WIDTH                   (PIXEL_DATA_WIDTH          ) 
)
 u_Sensor_Image_XYCrop(
//globel clock
    .clk                                (cmos_pclk                 ),// image pixel clock
    .rst_n                              (coms_ddr_init_done        ),
//CMOS Sensor interface
    .image_in_vsync                     (cmos_vsync                ),// H : Data Valid; L : Frame Sync(Set it by register)
    .image_in_href                      (cmos_href                 ),// H : Data vaild, L : Line Sync
    .image_in_de                        (cmos_de                   ),// H : Data Enable, L : Line Sync
    .image_in_data                      (cmos_data                 ),// 8 bits cmos data input
    .image_out_vsync                    (XYCrop_frame_vsync        ),// H : Data Valid; L : Frame Sync(Set it by register)
    .image_out_href                     (XYCrop_frame_href         ),// H : Data vaild, L : Line Sync
    .image_out_de                       (XYCrop_frame_de           ),// H : Data Enable, L : Line Sync
    .image_out_data                     (XYCrop_frame_data         ) // 8 bits cmos data input
);

reg                            r_XYCrop_frame_vsync     =0;
reg                            r_XYCrop_frame_href      =0;
reg                            r_XYCrop_frame_de        =0;
reg             [   7: 0]      r_XYCrop_frame_Gray      =0;
always @(posedge cmos_pclk) begin
     r_XYCrop_frame_vsync <= XYCrop_frame_vsync;
     r_XYCrop_frame_href <= XYCrop_frame_href;
     r_XYCrop_frame_de <= XYCrop_frame_de;
     r_XYCrop_frame_Gray <= XYCrop_frame_data;
end

wire                           cmos_frame_vsync           ;
wire                           cmos_frame_href            ;
wire            [   7: 0]      cmos_frame_Gray            ;
wire                           cmos_vsync_end             ;
assign     cmos_frame_vsync= r_XYCrop_frame_vsync;
assign     cmos_frame_href= r_XYCrop_frame_href && r_XYCrop_frame_de;
assign     cmos_frame_Gray= r_XYCrop_frame_Gray;
	



//=============================================================================
//  5. VIDEO PIPELINE ROUTING & TEST PATTERN
//=============================================================================
// DDR Test Pattern Generator ---> switch TEST_DDR to 0 for normal sensor input
//****************************************************************************************//
wire            [  23: 0]      test_lcd_data;                 // from lcd_display_test

// TEST_DDR/TEST_MODE & data source controlled by UART:
//   'L'=LCD test  |  'D'=DDR+pattern  |  'G'=DDR+gray
//   'S'/'R'=sensor RAW  |  'I'=demosaic  |  'W'=AWB  |  'C'=AWB+crop
localparam [1:0] ISP_MODE_RAW  = 2'd0;
localparam [1:0] ISP_MODE_RGB  = 2'd1;
localparam [1:0] ISP_MODE_AWB  = 2'd2;
localparam [1:0] ISP_MODE_CROP = 2'd3;
reg                             TEST_DDR = 1'b1;                // default: DDR test
reg                             TEST_MODE = 1'b0;               // default: DDR鈫扡CD
reg                             USE_GRAY = 1'b0;                // 0=XOR, 1=gray
reg                             USE_DYNAMIC = 1'b1;            // 0=static, 1=dynamic                // default: constant gray
reg             [   1: 0]      isp_mode = ISP_MODE_RAW;
reg             [   1: 0]      bayer_mirror_cmd = 2'b00;

localparam [9:0] ISP_GAIN_MIN      = 10'd128;  // 0.50x, Q8.8
localparam [9:0] ISP_GAIN_MAX      = 10'd768;  // 3.00x, Q8.8
localparam [9:0] ISP_GAIN_STEP     = 10'd16;   // 0.0625x per UART command
localparam [7:0] ISP_BRIGHT_MAX    = 8'd96;
localparam [7:0] ISP_BRIGHT_STEP   = 8'd4;
localparam [9:0] ISP_R_GAIN_DFLT   = 10'd409;  // 1.60x
localparam [9:0] ISP_G_GAIN_DFLT   = 10'd256;  // 1.00x
localparam [9:0] ISP_B_GAIN_DFLT   = 10'd384;  // 1.50x
localparam [9:0] ISP_ALL_GAIN_DFLT = 10'd320;  // 1.25x, brighten HDMI output
localparam [7:0] ISP_BRIGHT_DFLT   = 8'd8;

reg             [   9: 0]      isp_r_gain = ISP_R_GAIN_DFLT;
reg             [   9: 0]      isp_g_gain = ISP_G_GAIN_DFLT;
reg             [   9: 0]      isp_b_gain = ISP_B_GAIN_DFLT;
reg             [   9: 0]      isp_all_gain = ISP_ALL_GAIN_DFLT;
reg             [   7: 0]      isp_brightness = ISP_BRIGHT_DFLT;

always @(posedge clk_ctrl) begin
    if (DBG_LCD) begin
        TEST_MODE <= 1'b1; TEST_DDR <= 1'b1; USE_GRAY <= 1'b0; USE_DYNAMIC <= 1'b0; isp_mode <= ISP_MODE_RAW;
    end else if (DBG_DDR) begin
        TEST_MODE <= 1'b0; TEST_DDR <= 1'b1; USE_GRAY <= 1'b0; USE_DYNAMIC <= 1'b1; isp_mode <= ISP_MODE_RAW;
    end else if (DBG_XOR) begin
        TEST_MODE <= 1'b0; TEST_DDR <= 1'b1; USE_GRAY <= 1'b0; USE_DYNAMIC <= 1'b0; isp_mode <= ISP_MODE_RAW;
    end else if (DBG_GRAY) begin
        TEST_MODE <= 1'b0; TEST_DDR <= 1'b1; USE_GRAY <= 1'b1; USE_DYNAMIC <= 1'b0; isp_mode <= ISP_MODE_RAW;
    end else if (DBG_SEN || DBG_RAW) begin
        TEST_MODE <= 1'b0; TEST_DDR <= 1'b0; USE_GRAY <= 1'b0; USE_DYNAMIC <= 1'b0; isp_mode <= ISP_MODE_RAW;
    end else if (DBG_ISP) begin
        TEST_MODE <= 1'b0; TEST_DDR <= 1'b0; USE_GRAY <= 1'b0; USE_DYNAMIC <= 1'b0; isp_mode <= ISP_MODE_RGB;
    end else if (DBG_AWB) begin
        TEST_MODE <= 1'b0; TEST_DDR <= 1'b0; USE_GRAY <= 1'b0; USE_DYNAMIC <= 1'b0; isp_mode <= ISP_MODE_AWB;
    end else if (DBG_CROP) begin
        TEST_MODE <= 1'b0; TEST_DDR <= 1'b0; USE_GRAY <= 1'b0; USE_DYNAMIC <= 1'b0; isp_mode <= ISP_MODE_CROP;
    end else if (DBG_MIR0) begin
        bayer_mirror_cmd <= 2'b00;
    end else if (DBG_MIR1) begin
        bayer_mirror_cmd <= 2'b01;
    end else if (DBG_MIR2) begin
        bayer_mirror_cmd <= 2'b10;
    end else if (DBG_MIR3) begin
        bayer_mirror_cmd <= 2'b11;
    end
end

always @(posedge clk_ctrl or negedge sys_rst_n) begin
    if (!sys_rst_n) begin
        isp_r_gain     <= ISP_R_GAIN_DFLT;
        isp_g_gain     <= ISP_G_GAIN_DFLT;
        isp_b_gain     <= ISP_B_GAIN_DFLT;
        isp_all_gain   <= ISP_ALL_GAIN_DFLT;
        isp_brightness <= ISP_BRIGHT_DFLT;
    end else if (CMD_AWB_RESET) begin
        isp_r_gain     <= ISP_R_GAIN_DFLT;
        isp_g_gain     <= ISP_G_GAIN_DFLT;
        isp_b_gain     <= ISP_B_GAIN_DFLT;
        isp_all_gain   <= ISP_ALL_GAIN_DFLT;
        isp_brightness <= ISP_BRIGHT_DFLT;
    end else begin
        if (CMD_R_GAIN_UP)
            isp_r_gain <= (isp_r_gain >= (ISP_GAIN_MAX - ISP_GAIN_STEP)) ? ISP_GAIN_MAX : (isp_r_gain + ISP_GAIN_STEP);
        else if (CMD_R_GAIN_DN)
            isp_r_gain <= (isp_r_gain <= (ISP_GAIN_MIN + ISP_GAIN_STEP)) ? ISP_GAIN_MIN : (isp_r_gain - ISP_GAIN_STEP);

        if (CMD_G_GAIN_UP)
            isp_g_gain <= (isp_g_gain >= (ISP_GAIN_MAX - ISP_GAIN_STEP)) ? ISP_GAIN_MAX : (isp_g_gain + ISP_GAIN_STEP);
        else if (CMD_G_GAIN_DN)
            isp_g_gain <= (isp_g_gain <= (ISP_GAIN_MIN + ISP_GAIN_STEP)) ? ISP_GAIN_MIN : (isp_g_gain - ISP_GAIN_STEP);

        if (CMD_B_GAIN_UP)
            isp_b_gain <= (isp_b_gain >= (ISP_GAIN_MAX - ISP_GAIN_STEP)) ? ISP_GAIN_MAX : (isp_b_gain + ISP_GAIN_STEP);
        else if (CMD_B_GAIN_DN)
            isp_b_gain <= (isp_b_gain <= (ISP_GAIN_MIN + ISP_GAIN_STEP)) ? ISP_GAIN_MIN : (isp_b_gain - ISP_GAIN_STEP);

        if (CMD_ALL_GAIN_UP)
            isp_all_gain <= (isp_all_gain >= (ISP_GAIN_MAX - ISP_GAIN_STEP)) ? ISP_GAIN_MAX : (isp_all_gain + ISP_GAIN_STEP);
        else if (CMD_ALL_GAIN_DN)
            isp_all_gain <= (isp_all_gain <= (ISP_GAIN_MIN + ISP_GAIN_STEP)) ? ISP_GAIN_MIN : (isp_all_gain - ISP_GAIN_STEP);

        if (CMD_BRIGHT_UP)
            isp_brightness <= (isp_brightness >= (ISP_BRIGHT_MAX - ISP_BRIGHT_STEP)) ? ISP_BRIGHT_MAX : (isp_brightness + ISP_BRIGHT_STEP);
        else if (CMD_BRIGHT_DN)
            isp_brightness <= (isp_brightness <= ISP_BRIGHT_STEP) ? 8'd0 : (isp_brightness - ISP_BRIGHT_STEP);
    end
end

// DDR test: same grayscale data as LCD test pattern, for A/B comparison
//   L mode: grayscale -> LCD directly (bypass DDR)
//   D mode: grayscale -> DDR -> LCD (verify DDR loop)
//   Both modes show identical pattern -> any difference = DDR bug
wire            [   9: 0]      rgb_sum = {2'b0, test_lcd_data[23:16]}
                                      + {2'b0, test_lcd_data[15: 8]}
                                      + {2'b0, test_lcd_data[ 7: 0]};
wire            [   7: 0]      test_gray = rgb_sum[9:2];    // (R+G+B)/4

// DDR test: write @ 24MHz (clk_cmos), read @ 74.25MHz (clk_video)
// Separate clocks = no frame tearing ---> independent X Y counters
localparam H_ACTIVE = 12'd1280, H_BLANK = 12'd120, H_TOTAL = H_ACTIVE + H_BLANK;
localparam V_ACTIVE = 12'd720,  V_BLANK = 12'd10,  V_TOTAL = V_ACTIVE + V_BLANK;
reg  [11:0] ddr_test_x, ddr_test_y;
reg         ddr_test_vsync, ddr_test_href;
always @(posedge clk_cmos or negedge sys_rst_n) begin
    if (!sys_rst_n) begin
        ddr_test_x <= 0; ddr_test_y <= 0;
        ddr_test_vsync <= 0; ddr_test_href <= 0;
    end else begin
        ddr_test_x <= (ddr_test_x < H_TOTAL - 1) ? ddr_test_x + 1 : 0;
        if (ddr_test_x == H_TOTAL - 1)
            ddr_test_y <= (ddr_test_y < V_TOTAL - 1) ? ddr_test_y + 1 : 0;
        ddr_test_vsync <= (ddr_test_y < V_ACTIVE); 
        ddr_test_href  <= (ddr_test_y < V_ACTIVE && ddr_test_x < H_ACTIVE);
    end
end
// Dynamic mode: frame counter shifts XOR each frame ---> moving pattern
reg  [7:0] frame_color;
reg        ddr_vsync_d1;
always @(posedge clk_cmos or negedge sys_rst_n) begin
    if (!sys_rst_n) begin
        frame_color <= 0; ddr_vsync_d1 <= 0;
    end else begin
        ddr_vsync_d1 <= ddr_test_vsync;
        if (ddr_vsync_d1 && !ddr_test_vsync)           // vsync falling edge
            frame_color <= frame_color + 1'b1;
    end
end
// Second lcd_display_test @ 24MHz: uses ddr_test_x/y as coords, ddr_test_vsync for gating
wire [23:0] ddr_pattern_24m;
lcd_display_test #(.DELAY_TOP(24_000_000)) u_ddr_pattern(
    .clk      (clk_cmos),
    .rst_n    (sys_rst_n),
    .vsync    (ddr_test_vsync),
    .lcd_xpos (ddr_test_x),
    .lcd_ypos (ddr_test_y),
    .lcd_data (ddr_pattern_24m)
);
wire [9:0] ddr_pat_sum = {2'b0, ddr_pattern_24m[23:16]}
                       + {2'b0, ddr_pattern_24m[15: 8]}
                       + {2'b0, ddr_pattern_24m[ 7: 0]};
wire [7:0] ddr_pat_gray = ddr_pat_sum[9:2];    // (R+G+B)/4

(* ASYNC_REG = "TRUE" *) reg test_ddr_cmos_meta = 1'b1;
(* ASYNC_REG = "TRUE" *) reg test_ddr_cmos = 1'b1;
(* ASYNC_REG = "TRUE" *) reg use_gray_cmos_meta = 1'b0;
(* ASYNC_REG = "TRUE" *) reg use_gray_cmos = 1'b0;
(* ASYNC_REG = "TRUE" *) reg use_dynamic_cmos_meta = 1'b1;
(* ASYNC_REG = "TRUE" *) reg use_dynamic_cmos = 1'b1;
always @(posedge clk_cmos or negedge sys_rst_n) begin
    if (!sys_rst_n) begin
        test_ddr_cmos_meta <= 1'b1;
        test_ddr_cmos      <= 1'b1;
        use_gray_cmos_meta <= 1'b0;
        use_gray_cmos      <= 1'b0;
        use_dynamic_cmos_meta <= 1'b1;
        use_dynamic_cmos      <= 1'b1;
    end else begin
        test_ddr_cmos_meta <= TEST_DDR;
        test_ddr_cmos      <= test_ddr_cmos_meta;
        use_gray_cmos_meta <= USE_GRAY;
        use_gray_cmos      <= use_gray_cmos_meta;
        use_dynamic_cmos_meta <= USE_DYNAMIC;
        use_dynamic_cmos      <= use_dynamic_cmos_meta;
    end
end

wire [7:0] ddr_test_data = use_gray_cmos    ? 8'hA5 :
                           use_dynamic_cmos ? ddr_pat_gray :
                                         (ddr_test_x[7:0] ^ ddr_test_y[7:0]);

wire [7:0] wframe_data_w = test_ddr_cmos ? ddr_test_data : cmos_frame_Gray;
wire       wframe_vsync_w = test_ddr_cmos ? ddr_test_vsync : cmos_frame_vsync;
wire       wframe_href_w  = test_ddr_cmos ? (ddr_test_href & ddr_test_vsync) : cmos_frame_href;
wire       wframe_clk     = TEST_DDR ? clk_cmos : cmos_pclk;

wire            [  31: 0]      dbg_wr                      ;
wire            [  15: 0]      dbg_rd                      ;



//=============================================================================
//  [ RAW WRITE PATH ]
//  Keep DDR as 8-bit RAW/gray in this first ISP project. The color ISP runs after
//  DDR readback in the LCD clock domain, so the proven frame-buffer path stays intact.
//=============================================================================



//=============================================================================
//  6. MEMORY SUBSYSTEM (DDR3 & AXI4)
//=============================================================================
wire                           ui_clk                     ;//166.67MHz (4:1 mode)
wire                           ui_clk_sync_rst            ;

wire                           ddr3_aresetn               ;// Active low reset for DDR3 controller, synchronized to ui_clk
// AXI4 Write Address Channel
wire            [   3: 0]      s_axi_awid                 ;
wire            [  28: 0]      s_axi_awaddr               ;
wire            [   7: 0]      s_axi_awlen                ;
wire            [   2: 0]      s_axi_awsize               ;
wire            [   1: 0]      s_axi_awburst              ;
wire            [   0: 0]      s_axi_awlock               ;
wire            [   3: 0]      s_axi_awcache              ;
wire            [   2: 0]      s_axi_awprot               ;
wire            [   3: 0]      s_axi_awqos                ;
wire                           s_axi_awvalid              ;
wire                           s_axi_awready              ;
// AXI4 Write Data Channel
wire            [ 255: 0]      s_axi_wdata                ;
wire            [  31: 0]      s_axi_wstrb                ;
wire                           s_axi_wlast                ;
wire                           s_axi_wvalid               ;
wire                           s_axi_wready               ;
// AXI4 Write Response Channel
wire            [   3: 0]      s_axi_bid                  ;
wire            [   1: 0]      s_axi_bresp                ;
wire                           s_axi_bvalid               ;
wire                           s_axi_bready               ;
// AXI4 Read Address Channel
wire            [   3: 0]      s_axi_arid                 ;
wire            [  28: 0]      s_axi_araddr               ;
wire            [   7: 0]      s_axi_arlen                ;
wire            [   2: 0]      s_axi_arsize               ;
wire            [   1: 0]      s_axi_arburst              ;
wire            [   0: 0]      s_axi_arlock               ;
wire            [   3: 0]      s_axi_arcache              ;
wire            [   2: 0]      s_axi_arprot               ;
wire            [   3: 0]      s_axi_arqos                ;
wire                           s_axi_arvalid              ;
wire                           s_axi_arready              ;
// AXI4 Read Data Channel
wire            [   3: 0]      s_axi_rid                  ;
wire            [ 255: 0]      s_axi_rdata                ;
wire            [   1: 0]      s_axi_rresp                ;
wire                           s_axi_rlast                ;
wire                           s_axi_rvalid               ;
wire                           s_axi_rready               ;

assign     ddr3_aresetn = ~ui_clk_sync_rst;

wire                           lcd_clk                    ;
assign     lcd_clk      = clk_video    ;

wire            [  11: 0]      lcd_xpos                   ;
wire            [  11: 0]      lcd_ypos                   ;
wire            [   7: 0]      w_lcd_data                 ;
wire                           w_lcd_de                   ;
wire                           lcd_dclk_reg               ;

//=============================================================================
//  6.1 POST-DDR ISP PIPELINE (RAW8 -> RGB888)
//=============================================================================
(* ASYNC_REG = "TRUE" *) reg [1:0] test_mode_video_meta = 2'b00;
(* ASYNC_REG = "TRUE" *) reg [1:0] test_mode_video = 2'b00;
(* ASYNC_REG = "TRUE" *) reg [1:0] test_ddr_video_meta = 2'b11;
(* ASYNC_REG = "TRUE" *) reg [1:0] test_ddr_video = 2'b11;
(* ASYNC_REG = "TRUE" *) reg [1:0] isp_mode_video_meta = ISP_MODE_RAW;
(* ASYNC_REG = "TRUE" *) reg [1:0] isp_mode_video = ISP_MODE_RAW;
(* ASYNC_REG = "TRUE" *) reg [1:0] bayer_mirror_video_meta = 2'b00;
(* ASYNC_REG = "TRUE" *) reg [1:0] bayer_mirror_video = 2'b00;
(* ASYNC_REG = "TRUE" *) reg [9:0] isp_r_gain_video_meta = ISP_R_GAIN_DFLT;
(* ASYNC_REG = "TRUE" *) reg [9:0] isp_r_gain_video = ISP_R_GAIN_DFLT;
(* ASYNC_REG = "TRUE" *) reg [9:0] isp_g_gain_video_meta = ISP_G_GAIN_DFLT;
(* ASYNC_REG = "TRUE" *) reg [9:0] isp_g_gain_video = ISP_G_GAIN_DFLT;
(* ASYNC_REG = "TRUE" *) reg [9:0] isp_b_gain_video_meta = ISP_B_GAIN_DFLT;
(* ASYNC_REG = "TRUE" *) reg [9:0] isp_b_gain_video = ISP_B_GAIN_DFLT;
(* ASYNC_REG = "TRUE" *) reg [9:0] isp_all_gain_video_meta = ISP_ALL_GAIN_DFLT;
(* ASYNC_REG = "TRUE" *) reg [9:0] isp_all_gain_video = ISP_ALL_GAIN_DFLT;
(* ASYNC_REG = "TRUE" *) reg [7:0] isp_brightness_video_meta = ISP_BRIGHT_DFLT;
(* ASYNC_REG = "TRUE" *) reg [7:0] isp_brightness_video = ISP_BRIGHT_DFLT;
always @(posedge lcd_clk or negedge sys_rst_n) begin
    if (!sys_rst_n) begin
        test_mode_video_meta <= 2'b00;
        test_mode_video      <= 2'b00;
        test_ddr_video_meta  <= 2'b11;
        test_ddr_video       <= 2'b11;
        isp_mode_video_meta  <= ISP_MODE_RAW;
        isp_mode_video       <= ISP_MODE_RAW;
        bayer_mirror_video_meta <= 2'b00;
        bayer_mirror_video <= 2'b00;
        isp_r_gain_video_meta <= ISP_R_GAIN_DFLT;
        isp_r_gain_video <= ISP_R_GAIN_DFLT;
        isp_g_gain_video_meta <= ISP_G_GAIN_DFLT;
        isp_g_gain_video <= ISP_G_GAIN_DFLT;
        isp_b_gain_video_meta <= ISP_B_GAIN_DFLT;
        isp_b_gain_video <= ISP_B_GAIN_DFLT;
        isp_all_gain_video_meta <= ISP_ALL_GAIN_DFLT;
        isp_all_gain_video <= ISP_ALL_GAIN_DFLT;
        isp_brightness_video_meta <= ISP_BRIGHT_DFLT;
        isp_brightness_video <= ISP_BRIGHT_DFLT;
    end else begin
        test_mode_video_meta <= {2{TEST_MODE}};
        test_mode_video      <= test_mode_video_meta;
        test_ddr_video_meta  <= {2{TEST_DDR}};
        test_ddr_video       <= test_ddr_video_meta;
        isp_mode_video_meta  <= isp_mode;
        isp_mode_video       <= isp_mode_video_meta;
        bayer_mirror_video_meta <= bayer_mirror_cmd;
        bayer_mirror_video <= bayer_mirror_video_meta;
        isp_r_gain_video_meta <= isp_r_gain;
        isp_r_gain_video <= isp_r_gain_video_meta;
        isp_g_gain_video_meta <= isp_g_gain;
        isp_g_gain_video <= isp_g_gain_video_meta;
        isp_b_gain_video_meta <= isp_b_gain;
        isp_b_gain_video <= isp_b_gain_video_meta;
        isp_all_gain_video_meta <= isp_all_gain;
        isp_all_gain_video <= isp_all_gain_video_meta;
        isp_brightness_video_meta <= isp_brightness;
        isp_brightness_video <= isp_brightness_video_meta;
    end
end

wire                           isp_rgb_vsync              ;
wire                           isp_rgb_href               ;
wire                           isp_rgb_hsync              ;
wire            [   7: 0]      isp_rgb_pre_r              ;
wire            [   7: 0]      isp_rgb_pre_g              ;
wire            [   7: 0]      isp_rgb_pre_b              ;

VIP_RAW8_RGB888 #(
    .IMG_HDISP                          (IMAGE_HSIZE               ),
    .IMG_VDISP                          (IMAGE_YSIZE               )
) u_VIP_RAW8_RGB888 (
    .clk                                (lcd_clk                   ),
    .rst_n                              (sys_rst_n                 ),
    .mirror                             (bayer_mirror_video        ),
    .per_frame_vsync                    (lcd_vs                    ),
    .per_frame_href                     (lcd_de                    ),
    .per_frame_hsync                    (lcd_hs                    ),
    .per_img_RAW                        (w_lcd_data                ),
    .post_frame_vsync                   (isp_rgb_vsync             ),
    .post_frame_href                    (isp_rgb_href              ),
    .post_frame_hsync                   (isp_rgb_hsync             ),
    .post_img_red                       (isp_rgb_pre_r             ),
    .post_img_green                     (isp_rgb_pre_g             ),
    .post_img_blue                      (isp_rgb_pre_b             )
);

function automatic [7:0] isp_sat_bright8;
    input [11:0] value_i;
    input [ 7:0] offset_i;
    reg   [12:0] value_sum;
begin
    value_sum = {1'b0, value_i} + {5'b0, offset_i};
    isp_sat_bright8 = value_sum[12:8] ? 8'hFF : value_sum[7:0];
end
endfunction

// UART-adjustable white balance / brightness, Q8.8 gain format.
// Pipelined to avoid a long RGB gain -> global gain -> saturate path at 74.25MHz.
reg             [  17: 0]      isp_awb_r_color_mult = 18'd0;
reg             [  17: 0]      isp_awb_g_color_mult = 18'd0;
reg             [  17: 0]      isp_awb_b_color_mult = 18'd0;
reg             [  19: 0]      isp_awb_r_global_mult = 20'd0;
reg             [  19: 0]      isp_awb_g_global_mult = 20'd0;
reg             [  19: 0]      isp_awb_b_global_mult = 20'd0;
reg             [  11: 0]      isp_awb_r_scaled = 12'd0;
reg             [  11: 0]      isp_awb_g_scaled = 12'd0;
reg             [  11: 0]      isp_awb_b_scaled = 12'd0;
reg             [   7: 0]      isp_awb_r = 8'd0;
reg             [   7: 0]      isp_awb_g = 8'd0;
reg             [   7: 0]      isp_awb_b = 8'd0;

always @(posedge lcd_clk or negedge sys_rst_n) begin
    if (!sys_rst_n) begin
        isp_awb_r_color_mult  <= 18'd0;
        isp_awb_g_color_mult  <= 18'd0;
        isp_awb_b_color_mult  <= 18'd0;
        isp_awb_r_global_mult <= 20'd0;
        isp_awb_g_global_mult <= 20'd0;
        isp_awb_b_global_mult <= 20'd0;
        isp_awb_r_scaled      <= 12'd0;
        isp_awb_g_scaled      <= 12'd0;
        isp_awb_b_scaled      <= 12'd0;
        isp_awb_r             <= 8'd0;
        isp_awb_g             <= 8'd0;
        isp_awb_b             <= 8'd0;
    end else begin
        isp_awb_r_color_mult  <= isp_rgb_pre_r * isp_r_gain_video;
        isp_awb_g_color_mult  <= isp_rgb_pre_g * isp_g_gain_video;
        isp_awb_b_color_mult  <= isp_rgb_pre_b * isp_b_gain_video;
        isp_awb_r_global_mult <= isp_awb_r_color_mult[17:8] * isp_all_gain_video;
        isp_awb_g_global_mult <= isp_awb_g_color_mult[17:8] * isp_all_gain_video;
        isp_awb_b_global_mult <= isp_awb_b_color_mult[17:8] * isp_all_gain_video;
        isp_awb_r_scaled      <= isp_awb_r_global_mult[19:8];
        isp_awb_g_scaled      <= isp_awb_g_global_mult[19:8];
        isp_awb_b_scaled      <= isp_awb_b_global_mult[19:8];
        isp_awb_r             <= isp_sat_bright8(isp_awb_r_scaled, isp_brightness_video);
        isp_awb_g             <= isp_sat_bright8(isp_awb_g_scaled, isp_brightness_video);
        isp_awb_b             <= isp_sat_bright8(isp_awb_b_scaled, isp_brightness_video);
    end
end

wire                           isp_crop_vsync             ;
wire                           isp_crop_hsync             ;
wire                           isp_crop_de                ;
wire            [  23: 0]      isp_crop_data              ;

FrameBoundCrop #(
    .DATA_WIDTH                         (24                        ),
    .CNT_BITS                           (12                        ),
    .SKIP_ROWS                          (2                         ),
    .SKIP_COLS                          (2                         ),
    .TOTAL_ROWS                         (IMAGE_YSIZE               ),
    .TOTAL_COLS                         (IMAGE_HSIZE               )
) u_FrameBoundCrop (
    .clk_i                              (lcd_clk                   ),
    .rst_i                              (~sys_rst_n                ),
    .vs_i                               (isp_rgb_vsync             ),
    .hs_i                               (isp_rgb_hsync             ),
    .de_i                               (isp_rgb_href              ),
    .data_i                             ({isp_awb_r, isp_awb_g, isp_awb_b}),
    .vs_o                               (isp_crop_vsync            ),
    .hs_o                               (isp_crop_hsync            ),
    .de_o                               (isp_crop_de               ),
    .data_o                             (isp_crop_data             )
);

DDR3_0 ddr3 (
    // DDR3 Physical Interface
    .ddr3_dq                            (ddr3_dq                   ),// DDR3 data bus
    .ddr3_dqs_n                         (ddr3_dqs_n                ),// DDR3 data strobe negative
    .ddr3_dqs_p                         (ddr3_dqs_p                ),// DDR3 data strobe positive
    .ddr3_addr                          (ddr3_addr                 ),// DDR3 address bus
    .ddr3_ba                            (ddr3_ba                   ),// DDR3 bank address
    .ddr3_ras_n                         (ddr3_ras_n                ),// DDR3 row address strobe (active low)
    .ddr3_cas_n                         (ddr3_cas_n                ),// DDR3 column address strobe (active low)
    .ddr3_we_n                          (ddr3_we_n                 ),// DDR3 write enable (active low)
    .ddr3_reset_n                       (ddr3_reset_n              ),// DDR3 reset (active low)
    .ddr3_ck_p                          (ddr3_ck_p                 ),// DDR3 differential clock positive
    .ddr3_ck_n                          (ddr3_ck_n                 ),// DDR3 differential clock negative
    .ddr3_cke                           (ddr3_cke                  ),// DDR3 clock enable
    .ddr3_cs_n                          (ddr3_cs_n                 ),// DDR3 chip select (active low)
    .ddr3_dm                            (ddr3_dm                   ),// DDR3 data mask
    .ddr3_odt                           (ddr3_odt                  ),// DDR3 on-die termination enable

    // User Clock and Reset
    .ui_clk                             (ui_clk                    ),// MIG user clock output (1/4 DDR3 clock freq)
    .ui_clk_sync_rst                    (ui_clk_sync_rst           ),// MIG synchronous reset output
    .mmcm_locked                        (                          ),// MMCM locked indicator
    .aresetn                            (ddr3_aresetn              ),// AXI interconnect reset (active low)

    // Application Control Requests (unused)
    .app_sr_req                         (0                         ),// Self-refresh request
    .app_ref_req                        (0                         ),// Refresh request
    .app_zq_req                         (0                         ),// ZQ calibration request
    .app_sr_active                      (                          ),// Self-refresh active indicator
    .app_ref_ack                        (                          ),// Refresh acknowledge
    .app_zq_ack                         (                          ),// ZQ calibration acknowledge

    // AXI4 Write Address Channel
    .s_axi_awid                         (s_axi_awid                ),// Write address ID
    .s_axi_awaddr                       (s_axi_awaddr              ),// Write address
    .s_axi_awlen                        (s_axi_awlen               ),// Burst length
    .s_axi_awsize                       (s_axi_awsize              ),// Burst size
    .s_axi_awburst                      (s_axi_awburst             ),// Burst type
    .s_axi_awlock                       (s_axi_awlock              ),// Lock type
    .s_axi_awcache                      (s_axi_awcache             ),// Cache type
    .s_axi_awprot                       (s_axi_awprot              ),// Protection type
    .s_axi_awqos                        (s_axi_awqos               ),// QoS identifier
    .s_axi_awvalid                      (s_axi_awvalid             ),// Write address valid
    .s_axi_awready                      (s_axi_awready             ),// Write address ready

    // AXI4 Write Data Channel
    .s_axi_wdata                        (s_axi_wdata               ),// Write data
    .s_axi_wstrb                        (s_axi_wstrb               ),// Write byte strobe
    .s_axi_wlast                        (s_axi_wlast               ),// Write last beat
    .s_axi_wvalid                       (s_axi_wvalid              ),// Write data valid
    .s_axi_wready                       (s_axi_wready              ),// Write data ready

    // AXI4 Write Response Channel
    .s_axi_bready                       (s_axi_bready              ),// Write response ready
    .s_axi_bid                          (s_axi_bid                 ),// Write response ID
    .s_axi_bresp                        (s_axi_bresp               ),// Write response status
    .s_axi_bvalid                       (s_axi_bvalid              ),// Write response valid

    // AXI4 Read Address Channel
    .s_axi_arid                         (s_axi_arid                ),// Read address ID
    .s_axi_araddr                       (s_axi_araddr              ),// Read address
    .s_axi_arlen                        (s_axi_arlen               ),// Burst length
    .s_axi_arsize                       (s_axi_arsize              ),// Burst size
    .s_axi_arburst                      (s_axi_arburst             ),// Burst type
    .s_axi_arlock                       (s_axi_arlock              ),// Lock type
    .s_axi_arcache                      (s_axi_arcache             ),// Cache type
    .s_axi_arprot                       (s_axi_arprot              ),// Protection type
    .s_axi_arqos                        (s_axi_arqos               ),// QoS identifier
    .s_axi_arvalid                      (s_axi_arvalid             ),// Read address valid
    .s_axi_arready                      (s_axi_arready             ),// Read address ready

    // AXI4 Read Data Channel
    .s_axi_rready                       (s_axi_rready              ),// Read data ready
    .s_axi_rid                          (s_axi_rid                 ),// Read data ID
    .s_axi_rdata                        (s_axi_rdata               ),// Read data
    .s_axi_rresp                        (s_axi_rresp               ),// Read response status
    .s_axi_rlast                        (s_axi_rlast               ),// Read last beat
    .s_axi_rvalid                       (s_axi_rvalid              ),// Read data valid

    // Status and System
    .init_calib_complete                (ddr_init_done             ),// DDR3 init/calibration complete
    .device_temp                        (                          ),// FPGA device temperature (unused)

    // System Clock and Reset
    .sys_clk_i                          (clk_ddr_ref               ),// MIG system clock input 250MHz
    .clk_ref_i                          (clk_ddr_ref_200m          ),// IDELAYCTRL ref clock 200MHz
    .sys_rst                            (mig_sys_rst               ) // MIG system reset
    );

axi4_ctrl#(
    .ID_LEN                             (8                         ),
    .ADDR_LEN                           (32                        ),
    .DATA_LEN                           (256                       ),
    .DATA_SIZE                          (5                         ),// 2^5=32B=256-bit
    .STRB_LEN                           (                          ),
    .BURST_LEN                          (16                        ),
    .ADDR_INC                           (                          ),
    .W_WIDTH                            (8                         ),
    .R_WIDTH                            (8                         ),
    .BUF_SIZE                           (22                        ),
    .RD_END_ADDR                        (1280*720                  ),
    .BASE_ADDR                          (32'h0000_0000             )
)
 u_axi4_ctrl(
    .axi4_clk                           (ui_clk                    ),// AXI4 clock signal
    .axi4_rst_n                         (~ui_clk_sync_rst          ),// Active low reset signal for AXI4 interface
// AW - Write Address Channel
    .axi4_awid                          (s_axi_awid                ),// [7:0]--->[3:0]
    .axi4_awaddr                        (s_axi_awaddr              ),// [31:0]--->[28:0]
    .axi4_awlen                         (s_axi_awlen               ),// Burst length
    .axi4_awsize                        (s_axi_awsize              ),// Burst size
    .axi4_awburst                       (s_axi_awburst             ),// Burst type
    .axi4_awlock                        (s_axi_awlock              ),// [1:0]--->[0:0]
    .axi4_awcache                       (s_axi_awcache             ),// Cache type
    .axi4_awprot                        (s_axi_awprot              ),// Protection type
    .axi4_awqos                         (s_axi_awqos               ),// QoS identifier
    .axi4_awregion                      (                          ),// Not used by MIG
    .axi4_awvalid                       (s_axi_awvalid             ),// Write address valid
    .axi4_awready                       (s_axi_awready             ),// Write address ready
// W - Write Data Channel
    .axi4_wdata                         (s_axi_wdata               ),// Write data bus
    .axi4_wstrb                         (s_axi_wstrb               ),// Write byte strobe
    .axi4_wlast                         (s_axi_wlast               ),// Write last beat
    .axi4_wvalid                        (s_axi_wvalid              ),// Write data valid
    .axi4_wready                        (s_axi_wready              ),// Write data ready
// B - Write Response Channel
    .axi4_bid                           (s_axi_bid                 ),// [3:0]--->[7:0]
    .axi4_bresp                         (s_axi_bresp               ),// Write response
    .axi4_bvalid                        (s_axi_bvalid              ),// Write response valid
    .axi4_bready                        (s_axi_bready              ),// Write response ready
// AR - Read Address Channel
    .axi4_arid                          (s_axi_arid                ),// [7:0]--->[3:0]
    .axi4_araddr                        (s_axi_araddr              ),// [31:0]--->[28:0]
    .axi4_arlen                         (s_axi_arlen               ),// Burst length
    .axi4_arsize                        (s_axi_arsize              ),// Burst size
    .axi4_arburst                       (s_axi_arburst             ),// Burst type
    .axi4_arlock                        (s_axi_arlock              ),// [1:0]--->[0:0]
    .axi4_arcache                       (s_axi_arcache             ),// Cache type
    .axi4_arprot                        (s_axi_arprot              ),// Protection type
    .axi4_arqos                         (s_axi_arqos               ),// QoS identifier
    .axi4_arregion                      (                          ),// Not used by MIG
    .axi4_arvalid                       (s_axi_arvalid             ),// Read address valid
    .axi4_arready                       (s_axi_arready             ),// Read address ready
// R - Read Data Channel
    .axi4_rid                           (s_axi_rid                 ),// [3:0]--->[7:0]
    .axi4_rdata                         (s_axi_rdata               ),// Read data
    .axi4_rresp                         (s_axi_rresp               ),// Read response
    .axi4_rlast                         (s_axi_rlast               ),// Read last beat
    .axi4_rvalid                        (s_axi_rvalid              ),// Read data valid
    .axi4_rready                        (s_axi_rready              ),// Read data ready
// Write Frame Interface
    .wframe_pclk                        (wframe_clk                ),// Write clock
    .wframe_vsync                       (wframe_vsync_w            ),// Write frame vsync
    .wframe_data_en                     (wframe_href_w             ),// Write data enable
    .wframe_data                        (wframe_data_w             ),// Write frame pixel data
// Read Frame Interface
    .rframe_pclk                        (clk_video                 ),// LCD pixel clock 74.25MHz
    .rframe_vsync                       (lcd_vs                    ),// Read frame vsync
    .rframe_data_en                     (w_lcd_de                  ),// Read data request
    .rframe_data                        (w_lcd_data                ),// Read frame pixel data output
    // Debug ports for ILA
    .dbg_wr                             (dbg_wr                    ),
    .dbg_rd                             (dbg_rd                    )
);



//=============================================================================
//  7. DISPLAY SUBSYSTEM (LCD/HDMI) & SFP+
//=============================================================================
// LCD Test Pattern Generator ---> switch TEST_MODE to 0 after LCD is verified
//****************************************************************************************//
// TEST_MODE is now a reg controlled by UART (see above)
wire            [  23: 0]      lcd_data_src                 ;
wire            [  23: 0]      isp_raw_gray_data = {3{w_lcd_data}};
wire            [  23: 0]      isp_rgb_data      = {isp_rgb_pre_r, isp_rgb_pre_g, isp_rgb_pre_b};
wire            [  23: 0]      isp_awb_data      = {isp_awb_r, isp_awb_g, isp_awb_b};
wire            [  23: 0]      isp_mode_data     = (isp_mode_video == ISP_MODE_RGB ) ? isp_rgb_data  :
                                                   (isp_mode_video == ISP_MODE_AWB ) ? isp_awb_data  :
                                                   (isp_mode_video == ISP_MODE_CROP) ? isp_crop_data :
                                                                                 isp_raw_gray_data;

lcd_display_test #(
    .DELAY_TOP                          (74_250000                 ) // 1s per pattern
) u_lcd_display_test(
    .clk                                (lcd_clk                   ),
    .rst_n                              (sys_rst_n                 ),
    .vsync                              (lcd_vs                    ),// 0=blanking
    .lcd_xpos                           (lcd_xpos                  ),
    .lcd_ypos                           (lcd_ypos                  ),
    .lcd_data                           (test_lcd_data             )
);

// L mode bypasses DDR; D/X/G keep DDR gray tests; sensor modes select RAW/RGB/AWB/CROP.
assign lcd_data_src = test_mode_video[0] ? {3{test_gray}} :
                      test_ddr_video[0]  ? isp_raw_gray_data :
                                  isp_mode_data;

//****************************************************************************************//
// LCD Driver
lcd_driver u_lcd_driver(
    .clk                                (lcd_clk                   ),//720P@60FPS 74.25MHz
    .rst_n                              (sys_rst_n                 ),
    // LCD interface
    .lcd_clk                            (lcd_dclk_reg              ),
    .lcd_blank                          (                          ),
    .lcd_sync                           (                          ),
    .lcd_hs                             (lcd_hs                    ),
    .lcd_vs                             (lcd_vs                    ),
    .lcd_en                             (lcd_de                    ),
    .lcd_rgb                            ({lcd_red, lcd_green, lcd_blue}),

    // User interface
    .lcd_data                           (lcd_data_src              ),
    .lcd_request                        (w_lcd_de                  ),
    .lcd_xpos                           (lcd_xpos                  ),
    .lcd_ypos                           (lcd_ypos                  ) 
);


// Generate LCD pixel clock using ODDR
ODDR #(
    .DDR_CLK_EDGE                       ("OPPOSITE_EDGE"           ),// "OPPOSITE_EDGE" or "SAME_EDGE" 
    .INIT                               (1'b0                      ),// Initial value of Q: 1'b0 or 1'b1
    .SRTYPE                             ("SYNC"                    ) // Set/Reset type: "SYNC" or "ASYNC" 
) ODDR_inst (
    .Q                                  (lcd_dclk                  ),// 1-bit DDR output
    .C                                  (lcd_dclk_reg              ),// 1-bit clock input
    .CE                                 (1'b1                      ),// 1-bit clock enable input
    .D1                                 (1'b1                      ),// 1-bit data input (positive edge)
    .D2                                 (1'b0                      ),// 1-bit data input (negative edge)
    .R                                  (1'b0                      ),// 1-bit reset
    
.S                                  (1'b0                      ) // 1-bit set
);

// UART TX data: echo command, or status byte


always @(posedge clk_ctrl) begin
    if (uart_rx_done)
        uart_tx_data <= uart_rx_data;
    else if (!DBG_LCD && !DBG_DDR && !DBG_GRAY && !DBG_SEN && !DBG_RAW && !DBG_ISP && !DBG_AWB && !DBG_CROP)
      uart_tx_data <= {bayer_mirror_cmd, isp_mode, TEST_MODE, TEST_DDR, ddr_init_done, i2c_config_done};
end


//=============================================================================
//  8. ILA DEBUG PROBES
//=============================================================================
// ILA Debug ---> define USE_ILA to enable
// Camera debug probes (old DDR probes archived below)
//****************************************************************************************//
`ifdef USE_ILA
wire            [  31: 0]      ila_probe0;
wire            [  31: 0]      ila_probe1;
wire            [  15: 0]      ila_probe2;

// probe0: Sensor DVP raw pins + post-XYCrop pipeline
assign ila_probe0 = {
    cmos_pclk,                  // [31]     sensor pixel clock
    cmos_vsync,                 // [30]     sensor frame sync
    cmos_href,                  // [29]     sensor line sync
    cmos_data,                  // [28:21]  sensor data[7:0]
    cmos_xclk,                  // [20]     sensor master clock (FPGA鈫抯ensor)
    cmos_frame_vsync,           // [19]     post-XYCrop vsync
    cmos_frame_href,            // [18]     post-XYCrop href
    cmos_frame_Gray,            // [17:10]  post-XYCrop data[7:0]
    XYCrop_frame_vsync,         // [9]      XYCrop raw vsync
    XYCrop_frame_href           // [8]      XYCrop raw href
    // [7:0]  = XYCrop_frame_data[7:0] ? spare for future
};

// probe1: I2C config + init status + control
assign ila_probe1 = {
    cmos_sclk,                  // [31]     I2C clock
    cmos_sdat,                  // [30]     I2C data (I/O pin)
    cmos_sdat_oe,               // [29]     I2C data output enable
    cmos_sdat_out,              // [28]     I2C data output
    i2c_config_done,            // [27]     I2C config complete
    ddr_init_done,              // [26]     DDR calibration complete
    coms_ddr_init_done,         // [25]     combined init done
    sys_rst_n,                  // [24]     system reset (active low)
    i2c_config_index,           // [23:16]  I2C register index (stuck means NACK)
    dbg_cmd,                    // [15:8]   UART command register
    TEST_DDR,                   // [7]      DDR test mode
    TEST_MODE,                  // [6]      LCD bypass mode
    isp_mode,                   // [5:4]    post-DDR ISP display mode
    bayer_mirror_cmd,           // [3:2]    Bayer mirror phase
    2'b0                        // [1:0]    spare
};

// probe2: quick status summary
assign ila_probe2 = {
    i2c_config_done,            // [15]     I2C done
    ddr_init_done,              // [14]     DDR done
    coms_ddr_init_done,         // [13]     combined done
    sys_rst_n,                  // [12]     system reset
    TEST_DDR,                   // [11]     DDR test mode
    TEST_MODE,                  // [10]     LCD bypass mode
    isp_mode,                   // [9:8]    post-DDR ISP display mode
    cmos_frame_vsync,           // [7]      post-crop VSYNC
    cmos_frame_href,            // [6]      post-crop HREF
    wframe_vsync_w,             // [5]      write VSYNC
    wframe_href_w,              // [4]      write HREF
    cmos_pclk,                  // [3]      sensor PCLK
    cmos_xclk,                  // [2]      sensor XCLK
    cmos_sclk,                  // [1]      I2C SCLK
    cmos_sdat                   // [0]      I2C SDAT
};

ila_0 u_ila_0 (
    .clk                                (clk_ddr_ref_200m          ),
    .probe0                             (ila_probe0                ),
    .probe1                             (ila_probe1                ),
    .probe2                             (ila_probe2                )
);
`endif

// --- Archived DDR debug probes ---
// assign ila_probe0 = {
//     wframe_data_w,              // [31:24]  write data INTO FIFO
//     s_axi_wdata[7:0],           // [23:16]  write data on AXI bus
//     wframe_vsync_w,             // [15]     write vsync
//     wframe_href_w,              // [14]     write data enable
//     dbg_wr[7],                  // [13]     r_weof_pending
//     dbg_wr[6],                  // [12]     w_wfifo_empty
//     s_axi_wlast,                // [11]     write last
//     s_axi_wready,               // [10]     write ready
//     s_axi_wvalid,               // [9]      write valid
//     s_axi_awready,              // [8]      aw ready
//     s_axi_awvalid,              // [7]      aw valid
//     dbg_wr[28:24],              // [6:2]    rc_wfifo_we
//     dbg_wr[1:0]                 // [1:0]    state_write
// };
// assign ila_probe1 = {
//     w_lcd_data,                 // [31:24]  pixel data TO LCD
//     s_axi_rdata[7:0],           // [23:16]  read data from DDR
//     lcd_vs,                     // [15]     LCD/read vsync
//     lcd_de,                     // [14]     LCD active area
//     w_lcd_de,                   // [13]     LCD requesting data
//     s_axi_rlast,                // [12]     read last
//     s_axi_rvalid,               // [11]     read data valid
//     s_axi_rready,               // [10]     read ready
//     s_axi_arvalid,              // [9]      ar valid
//     s_axi_arready,              // [8]      ar ready
//     dbg_rd[10],                 // [7]      read_ddr_init_flag
//     dbg_rd[11],                 // [6]      r_rframe_inc
//     dbg_rd[9:8],                // [5:4]    rc_rframe_index
//     dbg_rd[1:0],                // [3:2]    rd_state
//     2'b0                        // [1:0]
// };
// assign ila_probe2 = {
//     mig_sys_rst,                // [15]
//     wframe_vsync_w,             // [14]     write vsync
//     lcd_vs,                     // [13]     read/LCD vsync
//     dbg_wr[5],                  // [12]     r_wframe_inc
//     dbg_rd[11],                 // [11]     r_rframe_inc
//     dbg_wr[4:3],                // [10:9]   rc_wframe_index
//     dbg_rd[9:8],                // [8:7]    rc_rframe_index
//     TEST_MODE,                  // [6]
//     TEST_DDR,                   // [5]
//     sys_rst_n,                  // [4]
//     ui_clk_sync_rst,            // [3]
//     ddr_init_done,              // [2]
//     s_axi_bvalid,               // [1]
//     s_axi_bready                // [0]
// };

endmodule
